<?php

namespace ETAP\EmpruntBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class UtilisateurController__JMSInjector
{
    public static function inject($container) {
        $instance = new \ETAP\EmpruntBundle\Controller\UtilisateurController();
        return $instance;
    }
}
